"""add user.role (client/admin)

Revision ID: a1cf86800621
Revises: e0eddb785d17
Create Date: 2026-06-08 04:05:34.887927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1cf86800621'
down_revision: Union[str, Sequence[str], None] = 'e0eddb785d17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # add_column does NOT auto-create the enum type (only create_table does) — create it first.
    user_role = sa.Enum('client', 'admin', name='user_role')
    user_role.create(op.get_bind(), checkfirst=True)
    op.add_column(
        'users',
        sa.Column(
            'role',
            sa.Enum('client', 'admin', name='user_role', create_type=False),
            server_default='client',
            nullable=False,
        ),
    )
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_column('users', 'role')
    sa.Enum(name='user_role').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
